kind: Pod
apiVersion: v1
metadata:
  name: testpod3
  annotations:
     description: My testpod3 with more than one container
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo hello-sharad; sleep 5; done"]
    - name: c01
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo hello-shree; sleep 5; done"]
