kind: Pod
apiVersion: v1
metadata:
   name: labelspod1
   labels:
     day: fri
     class: kubernetes
spec:
  containers:
    - name: resaource
      image: centos
      command: ["/bin/bash","-c","while true; do echo Hello-Sharad; sleep 5; done"]
